Convert connector to webhook
rossumai/check-sum-connector-nodejs pull request #9
Opened 2020-09-16 09:02 UTC by evelyn9191

2020-09-21 16:13 UTC, janmarsicek requested changes
also I would find it very useful to provide a testing schema for the queue, I had hard times debugging it and running to `Error parsing annotation` error a lot since my testing schema uses different schema IDs... but if it works with some default schema we use for registration, it is ok 👌

2020-09-21 16:13 UTC, janmarsicek commented on webhook.js
> +  const sum = vatDetails.reduce((s, i) => s + floatValue(findByPath(i.children, ['vat_detail_tax'])), 0);
was this working for you? I think there is `.content` missing as `findByPath` helper returns the whole datapoint object. When you access the content, `floatValue` will pick the value from it...

2020-09-21 16:13 UTC, janmarsicek commented on webhook.js
> +  return Math.abs(sum - floatValue(vatTotal)) <= tolerance;
should be `vatTotal.content` probably...

2020-09-21 16:13 UTC, janmarsicek commented on webhook.js
> +const floatValue = ({ value }) => parseFloat(value);
OK! ideally, `floatValue` function should look like this: `({ content: { value } }) => parseFloat(value)` and you can ignore my previous comments 😄

2020-09-22 05:56 UTC, evelyn9191 commented
It works with the default EU demo schema. But I added it to the code, it's better like this. Thanks for the note!

2020-09-22 06:28 UTC, janmarsicek approved these changes

2020-09-22 07:01 UTC, merged